display_errors = Off
log_errors = On
error_log = /var/log/php_errors.log
memory_limit = 256M
upload_max_filesize = 50M
post_max_size = 50M
max_execution_time = 60

; Desactivar short tags
short_open_tag = Off

; Extensiones que solemos usar
extension=swoole.so
extension=redis.so

; Opcional: desactivar uso de shortnames swoole
swoole.use_shortname=Off
